package com.raven.login;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.event.ComponentListener;



public class Login extends javax.swing.JFrame {

    private JLabel avatarLabel;
    private JTextField emailField;
    private JPasswordField passwordField;
    private JButton signInButton;

    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        myTextField1 = new com.raven.swing.textfield.MyTextField();
        myPassword1 = new com.raven.swing.textfield.MyPassword();
        imageAvatar1 = new com.raven.swing.ImageAvatar();
        imageAvatar2 = new com.raven.swing.ImageAvatar();
        imageAvatar3 = new com.raven.swing.ImageAvatar();
        imageAvatar4 = new com.raven.swing.ImageAvatar();
        button1 = new com.raven.swing.Button();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        imageAvatar5 = new com.raven.swing.ImageAvatar();
        imageAvatar6 = new com.raven.swing.ImageAvatar();
        imageAvatar7 = new com.raven.swing.ImageAvatar();
        imageAvatar8 = new com.raven.swing.ImageAvatar();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        myTextField1.setHint("Email");
        myTextField1.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/swing/textfield/mail.png"))); // NOI18N

        myPassword1.setHint("Password");
        myPassword1.setPrefixIcon(new javax.swing.ImageIcon(getClass().getResource("/com/raven/swing/textfield/key.png"))); // NOI18N

        imageAvatar1.setBorderSize(0);
        imageAvatar1.setBorderSpace(0);
        imageAvatar1.setGradientColor2(new java.awt.Color(42, 98, 199));
        imageAvatar1.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/raven/login/logo.png")));
        imageAvatar1.setBounds(10, 10, 200, 100);

        imageAvatar2.setBorderSize(2);
        imageAvatar2.setBorderSpace(2);
        imageAvatar2.setGradientColor2(new java.awt.Color(42, 98, 199));
        imageAvatar2.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/raven/login/profile.jpg"))); // NOI18N
        imageAvatar1.add(imageAvatar2);
        imageAvatar2.setBounds(0, 0, 0, 0);

        imageAvatar3.setBorderSize(2);
        imageAvatar3.setBorderSpace(2);
        imageAvatar3.setGradientColor2(new java.awt.Color(42, 98, 199));
        imageAvatar3.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/raven/login/profile.jpg"))); // NOI18N

        imageAvatar4.setBorderSize(2);
        imageAvatar4.setBorderSpace(2);
        imageAvatar4.setGradientColor2(new java.awt.Color(42, 98, 199));
        imageAvatar4.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/raven/login/profile.jpg"))); // NOI18N
        imageAvatar3.add(imageAvatar4);
        imageAvatar4.setBounds(0, 0, 0, 0);

        imageAvatar1.add(imageAvatar3);
        imageAvatar3.setBounds(0, 0, 0, 0);

        button1.setBackground(new java.awt.Color(240, 68, 68));
        button1.setForeground(new java.awt.Color(255, 255, 255));
        button1.setText("Sign In");
        button1.setFont(new java.awt.Font("sansserif", 1, 14)); // NOI18N
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });

        jRadioButton1.setText("AM");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("Resident");
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Welcome User");

        imageAvatar5.setBorderSize(2);
        imageAvatar5.setBorderSpace(2);
        imageAvatar5.setGradientColor2(new java.awt.Color(42, 98, 199));
        imageAvatar5.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/raven/login/profile.jpg"))); // NOI18N

        imageAvatar6.setBorderSize(2);
        imageAvatar6.setBorderSpace(2);
        imageAvatar6.setGradientColor2(new java.awt.Color(42, 98, 199));
        imageAvatar6.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/raven/login/profile.jpg"))); // NOI18N
        imageAvatar5.add(imageAvatar6);
        imageAvatar6.setBounds(0, 0, 0, 0);

        imageAvatar7.setBorderSize(2);
        imageAvatar7.setBorderSpace(2);
        imageAvatar7.setGradientColor2(new java.awt.Color(42, 98, 199));
        imageAvatar7.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/raven/login/profile.jpg"))); // NOI18N

        imageAvatar8.setBorderSize(2);
        imageAvatar8.setBorderSpace(2);
        imageAvatar8.setGradientColor2(new java.awt.Color(42, 98, 199));
        imageAvatar8.setImage(new javax.swing.ImageIcon(getClass().getResource("/com/raven/login/profile.jpg"))); // NOI18N
        imageAvatar7.add(imageAvatar8);
        imageAvatar8.setBounds(0, 0, 0, 0);

        imageAvatar5.add(imageAvatar7);
        imageAvatar7.setBounds(0, 0, 0, 0);

        // Load the image
        ImageIcon originalImageIcon = new ImageIcon(getClass().getResource("/com/raven/login/apartment.jpeg"));

        // Create a component listener for the label
        ComponentListener labelComponentListener = new ComponentAdapter() {
            @Override
            public void componentResized(ComponentEvent e) {
                // Get the size of the label
                int labelWidth = jLabel2.getWidth();
                int labelHeight = jLabel2.getHeight();

                // Only perform scaling if the label size is non-zero
                if (labelWidth > 0 && labelHeight > 0) {
                    // Scale the image to fit the label size
                    Image scaledImage = originalImageIcon.getImage().getScaledInstance(labelWidth, labelHeight, Image.SCALE_SMOOTH);

                    // Create a new ImageIcon with the scaled image
                    ImageIcon scaledImageIcon = new ImageIcon(scaledImage);

                    // Set the scaled image icon as the icon for the JLabel
                    jLabel2.setIcon(scaledImageIcon);
                }
            }
        };

        // Add the component listener to the label
        jLabel2.addComponentListener(labelComponentListener);

        // Set the text for the JLabel
        jLabel2.setText("jLabel2");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTextField1.setText("Choose One:");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(89, 89, 89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(myTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                                .addComponent(myPassword1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jRadioButton1)
                                .addGap(64, 64, 64)
                                .addComponent(jRadioButton2)))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(586, 586, 586)
                    .addComponent(imageAvatar5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(imageAvatar1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(33, 33, 33)
                        .addComponent(myTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(myPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2))
                        .addGap(42, 42, 42)
                        .addComponent(button1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(62, 62, 62))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(imageAvatar5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(416, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_button1ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    public Login(JLabel avatarLabel, JTextField emailField, JPasswordField passwordField, JButton signInButton) {
        this.avatarLabel = avatarLabel;
        this.emailField = emailField;
        this.passwordField = passwordField;
        this.signInButton = signInButton;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.swing.Button button1;
    private com.raven.swing.ImageAvatar imageAvatar1;
    private com.raven.swing.ImageAvatar imageAvatar2;
    private com.raven.swing.ImageAvatar imageAvatar3;
    private com.raven.swing.ImageAvatar imageAvatar4;
    private com.raven.swing.ImageAvatar imageAvatar5;
    private com.raven.swing.ImageAvatar imageAvatar6;
    private com.raven.swing.ImageAvatar imageAvatar7;
    private com.raven.swing.ImageAvatar imageAvatar8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextField1;
    private com.raven.swing.textfield.MyPassword myPassword1;
    private com.raven.swing.textfield.MyTextField myTextField1;
    // End of variables declaration//GEN-END:variables
}
